import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";

// graphqlとのAPI接続
const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.hygraph.com/v2/clbohkjyq0dt701t5b58j1trr/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      photo {
        createdBy {
          id
        }
        url
      }
    }
  }
`;

// SSG
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);

  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.title}>
          <h2>Next.jsとGraphQLブログ</h2>
        </div>
        <div className={styles.gridWrapper}>
          {posts.map((post) => (
            <BlogCard
              photo={post.photo}
              title={post.title}
              author={post.author}
              date={post.datePublished}
              slug={post.slug}
              key={post.id}
            />
          ))}
        </div>
      </main>
    </div>
  );
}
